  // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARnhDhhdK6SpVyb76iv8ieQRwm5ihNsfo',
    appId: '1:309057522914:web:973c967911b95bd4e2a2bb',
    messagingSenderId: '309057522914',
    projectId: 'firebasics-6e34d',
    authDomain: 'firebasics-6e34d.firebaseapp.com',
    databaseURL: 'https://firebasics-6e34d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firebasics-6e34d.firebasestorage.app',
    measurementId: 'G-4M8CVJWLET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt-iJM-eazSp_vCGRT_LIYklJcjUi6A9s',
    appId: '1:309057522914:android:5fa315388c08e108e2a2bb',
    messagingSenderId: '309057522914',
    projectId: 'firebasics-6e34d',
    databaseURL: 'https://firebasics-6e34d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firebasics-6e34d.firebasestorage.app',
  );

}